config/routes.rb
Refinery::Application.routes.draw do
  get '/contact', :to => 'submissions#new', :as => 'new_submission'
  resources :contact,
            :only => :create,
            :as => :submissions,
            :controller => 'submissions' do
    collection do
      get :thank_you
    end
  end

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :submissions, :only => [:index, :show, :destroy] do
      collection do
        get :spam
      end
      member do
        get :toggle_spam
      end
    end
    resources :submission_settings, :only => [:edit, :update]
  end
end

app/models/submission.rb
class Submission < ActiveRecord::Base

  validates :first_name, :presence => true
  validates :message, :presence => true
  validates :email, :format=> { :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i }

  acts_as_indexed :fields => [:first_name, :last_name, :email, :phone, :message, :your_interest, :how_did_you_find_us, :method_of_contact, :user_ip, :user_agent, :referrer]

  default_scope :order => 'created_at DESC'
  
  before_create :check_for_spam
  
  def name
    [self.first_name, self.last_name].join(' ')
  end
  
  def request=(request)
    self.user_ip    = request.remote_ip
    self.user_agent = request.env['HTTP_USER_AGENT']
    self.referrer   = request.env['HTTP_REFERER']
  end

  def check_for_spam
    self.spam = Akismetor.spam?(akismet_attributes)
    true # return true so it doesn't stop save
  end

  def akismet_attributes
    {
      :key                  => akismet_key,
      :blog                 => full_site_url,
      :user_ip              => user_ip,
      :user_agent           => user_agent,
      :comment_author       => name,
      :comment_author_email => email,
      :comment_author_url   => email.split('@')[1],
      :comment_content      => message
    }
  end

  def mark_as_spam!
    self.spam = true
    self.save!
    Akismetor.submit_spam(akismet_attributes)
  end

  def mark_as_ham!
    self.spam = false
    self.save!
    Akismetor.submit_ham(akismet_attributes)
  end

  def self.latest(number = 7, include_spam = false)
    include_spam ? limit(number) : ham.limit(number)
  end
  
  def akismet_key
    RefinerySetting.find_or_set(:akismet_key, "Akismet Key")  
  end
  
  def full_site_url
    RefinerySetting.find_or_set(:full_site_url, "http://example.com") 
  end
  
  def self.confirmation_body
    RefinerySetting.find_or_set(:submission_confirmation_body,
      "Thank you for filling out our contact form %name%,\n\nThis email is a receipt to confirm we have received your information and we'll be in touch shortly.\n\nThanks."
    )
  end

  def confirmation_subject(locale='en')
    RefinerySetting.find_or_set("submission_confirmation_subject_#{locale}".to_sym,
                                "Thank you for contacting us.")
  end

  def confirmation_subject=(value)
    value.first.keys.each do |locale|
      RefinerySetting.set("submission_confirmation_subject_#{locale}".to_sym, value.first[locale.to_sym])
    end
  end

  def self.confirmation_message(locale='en')
    self.confirmation_body
    RefinerySetting.find_or_set("submission_confirmation_message_#{locale}".to_sym,
                                RefinerySetting[:submission_confirmation_body])
  end

  def self.confirmation_message=(value)
    value.first.keys.each do |locale|
      RefinerySetting.set("submission_confirmation_message_#{locale}".to_sym, value.first[locale.to_sym])
    end
  end

  def notification_recipients
    RefinerySetting.find_or_set(:submission_notification_recipients, "james@jamesrissler.com")
  end

  def notification_subject
    RefinerySetting.find_or_set(:submission_notification_subject,
                                "New contact form submission from your website")
  end

  def self.send_confirmation?
    RefinerySetting.find_or_set(:submission_send_confirmation, true)
  end

end

app/controllers/admin/submissions_controller.rb
class Admin::SubmissionsController < Admin::BaseController

  crudify :submission, :title_attribute => "name", :order => "created_at DESC"
  helper_method :group_by_date

  before_filter :find_all_ham, :only => [:index]
  before_filter :find_all_spam, :only => [:spam]
  before_filter :get_spam_count, :only => [:index, :spam]

  def index
    @submissions = @submissions.with_query(params[:search]) if searching?
    @submissions = @submissions.paginate({:page => params[:page]})
  end

  def spam
    self.index
    render :action => 'index'
  end

  def toggle_spam
    find_submission
    if params[:mark_as] == "ham"
      @submission.mark_as_ham!
    else
      @submission.mark_as_spam!
    end  

    redirect_to :back
  end

protected

  def find_all_ham
    @submissions = Submission.where(:spam => false)
  end

  def find_all_spam
    @submissions = Submission.where(:spam => true)
  end

  def get_spam_count
    @spam_count = Submission.count(:conditions => {:spam => true})
  end

end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_filter :find_page, :only => [:create, :new]
  
  def thank_you
    @page = Page.find_by_link_url("/contact/thank_you", :include => [:parts, :slugs])
  end

  def new
    @submission = Submission.new
  end

  def create
    @submission = Submission.new(params[:submission])
    @submission.request = request
    
    if @submission.save
      if !@submission.spam?
        begin
          SubmissionMailer.notification(@submission, request).deliver
        rescue
          logger.warn "There was an error delivering an submission notification.\n#{$!}\n"
        end
        
        begin
          SubmissionMailer.confirmation(@submission, request).deliver
        rescue
          logger.warn "There was an error delivering an submission confirmation:\n#{$!}\n"
        end if Submission.send_confirmation?        
      end
      redirect_to thank_you_submissions_url
    else
      render :action => 'new'
    end
  end

protected

  def find_page
    @page = Page.find_by_link_url('/contact', :include => [:parts, :slugs])
  end

end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/admin/submissions/_confirmation_email_form.html.erb
<%= form_for([:admin, @refinery_setting], :url => (@url_override || @url)) do |f| %>

  <p>
    <%= t('.explanation') %>
  </p>
  <p>
    <%= t('.below_edit_email_sent') %>
  </p>
  <table id='submission'>
    <tr>
      <td>
        <label class='stripped'><%= t('.to') %></label>
      </td>
      <td>
        <%= t('.the_customer_making_submission') %>
      </td>
    </tr>
    <tr>
      <td>
        <label class='stripped'><%= t('.from') %></label>
      </td>
      <td>
        <%= "#{RefinerySetting[:site_name]} &lt;no-reply@#{request.domain(RefinerySetting.find_or_set(:tld_length, 1))}&gt;".html_safe %>
      </td>
    </tr>
    <% (RefinerySetting.get("i18n_translation_frontend_locales", :scoping => 'refinery')||[I18n.locale]).each do |locale| %>
      <tr>
        <td>
          <label class='stripped'><%= t('.subject') %> (<%= locale.to_s %>)</label>
        </td>
        <td>
          <%= text_field_tag "subject[][#{locale.to_s}]", SubmissionSetting.confirmation_subject(locale),
                             :class => 'widest' %>
        </td>
      </tr>
      <tr>
        <td valign='top'>
          <%= f.label :value, t('.message'),
                      :class => 'stripped' %> (<%= locale.to_s %>)
        </td>
        <td>
          <%= text_area_tag "message[][#{locale.to_s}]", SubmissionSetting.confirmation_message(locale), # required, we can't use :value
                          :rows => "5",
                          :class => 'widest' %>
          <br/>
          <em><%= t('.note') %></em>
        </td>
      </tr>
    <% end %>
  </table>

  <%= render :partial => "/shared/admin/form_actions",
             :locals => {
               :f => f,
               :continue_editing => false,
               :cancel_url => admin_submissions_url,
               :hide_delete => true
             } %>
<% end %>

app/views/admin/submissions/_notification_recipients_form.html.erb
<%= form_for([:admin, @refinery_setting], :url => (@url_override || @url)) do |f| %>

  <div class='field'>
    <span class='label_with_help'>
      <%= f.label :value, t('.submission_settings_value_name') %>
    </span>
    <%= f.text_field :value, :value => f.object.value, # required, we can't use :value
                     :class => "larger widest" %>
  </div>

  <p>
    <%= t('.hint') %>
  </p>
  <p>
    <%= t('.example') %>
  </p>

  <%= render :partial => "/shared/admin/form_actions",
             :locals => {
               :f => f,
               :continue_editing => false,
               :cancel_url => admin_submissions_url,
               :hide_delete => true
             } %>
<% end %>

app/views/admin/submissions/_submenu.html.erb
<div id='actions'>
  <ul>
    <li>
      <%= render :partial => "/shared/admin/search", :locals => {:url => request.path} %>
    </li>
    <li <%= "class='selected'" if params[:action] == "index" %>>
      <%= link_to t('.inbox'), admin_submissions_url, :class => "email_icon" %>
    </li>
    <li <%= "class='selected'" if params[:action] == "spam" %>>
      <% if @spam_count > 0 %>
        <%= link_to "#{t('.spam')} (#{@spam_count})", spam_admin_submissions_url, :class => "spam_icon" %>
      <% else %>
        <%= link_to t('.spam'), spam_admin_submissions_url, :class => "spam_empty_icon" %>
      <% end %>
    </li>

  </ul>
</div>

app/views/admin/submissions/_submission.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>'>
  <span class='title'>
    <%= link_to submission.name, admin_submission_url(submission) %> <%= t('.said') %>
    <span class="preview"><%= truncate(strip_tags(submission.message), :length => 60) -%></span>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag('delete.png'), admin_submission_url(submission),
              { :method => :delete,
                :confirm => t('shared.admin.delete.message', :title => submission.name) },
                :class => "cancel confirm-delete",
                :title => t('admin.inquiries.delete') -%>

    <%= link_to refinery_icon_tag('zoom.png'), admin_submission_url(submission),
                :title => t('.read_submission') -%>

    <% if submission.spam? %>
      <%= link_to refinery_icon_tag('email.png'), toggle_spam_admin_submission_url(submission, :mark_as => "ham"),
                  :title => t('.mark_as_ham') -%>
    <% else %>
      <%= link_to refinery_icon_tag('bin_closed.png'), toggle_spam_admin_submission_url(submission, :mark_as => "spam"),
                  :title => t('.mark_as_spam') -%>
    <% end %>
  </span>
</li>

app/views/admin/submissions/index.html.erb
<%= render :partial => "submenu" %>
<div id='records'>
  <% if searching? %>
    <h2><%= t('shared.admin.search.results_for', :query => params[:search]) %></h2>
    <% if @submissions.any? %>
      <%= will_paginate @submissions %>
      <ul>
        <%= render :partial => "submission", :collection => @submissions %>
      </ul>
      <%= will_paginate @submissions %>
    <% else %>
      <p><%= t('shared.admin.search.no_results') %></p>
    <% end %>
  <% else %>
    <% if @submissions.any? -%>
      <%= will_paginate @submissions %>
      <% group_by_date(@submissions).each do |container| %>
        <h3><%= l((submission_group = container.last).first.created_at, :format => :short) %></h3>
        <ul>
          <%= render :partial => 'submission', :collection => submission_group %>
        </ul>
      <% end %>
      <%= will_paginate @submissions %>
    <% else -%>
      <p>
        <strong><%= t(".no_#{action_name == 'index' ? 'submissions' : 'spam'}") %></strong>
      </p>
    <% end -%>
  <% end %>
</div>

app/views/admin/submissions/show.html.erb
<div id='actions'>
  <h2><%= t('.details')%></h2>
  <p>
    <strong><%= t('.age') %>:</strong> <%= time_ago_in_words(@submission.created_at) %>
  </p>
  <% if @submission.spam? %>
    <p>
      <strong><%= t('.spam') %>:</strong> <%= t('.spam_yes') %>
    </p>
  <% end %>
  <h2><%= t('.actions') %></h2>
  <ul>
    <li>
      <%= link_to t('.back_to_all_submissions'), {:action => 'index'}, :class => "back_icon" %>
    </li>
    <li>
      <%= link_to t('admin.submissions.delete'),
                  admin_submission_url(@submission),
                  :class => 'delete_icon no-tooltip confirm-delete',
                  :title => t('admin.submissions.delete'),
                  :confirm => t('shared.admin.delete.message', :title => @submission.name),
                  :method => :delete %>
    </li>
  </ul>
</div>
<div id='records'>
  <h2><%= t('.submission') %></h2>
  <table id='submission'>
    <tr>
      <td>
        <strong><%= t('.to') %></strong>
      </td>
      <td>
        <%= RefinerySetting[:site_name] %>
      </td>
    </tr>
    <tr>
      <td>
        <strong><%= t('.from') %></strong>
      </td>
      <td>
        <%= @submission.name %> [<%= mail_to @submission.email, @submission.email, {:title => t('.click_to_email')} %>]
      </td>
    </tr>
    <% unless @submission.phone.blank? %>
      <tr>
        <td>
          <strong><%= t('.phone') %></strong>
        </td>
        <td>
          <%= @submission.phone %>
        </td>
      </tr>
    <% end %>
    <% unless @submission.how_did_you_find_us.blank? %>
      <tr>
        <td>
          <strong>
            How they found us
          </strong>
        </td>
        <td>
          <%= @submission.how_did_you_find_us %>
        </td>
      </tr>
    <% end %>
    <% unless @submission.your_interest.blank? %>
      <tr>
        <td>
          <strong>
            Their interest
          </strong>
        </td>
        <td>
          <%= @submission.your_interest %>
        </td>
      </tr>
    <% end %>
    <tr>
      <td>
        <strong><%= t('.date') %></strong>
      </td>
      <td>
        <%= l(Date.parse(@submission.created_at.to_s), :format => :long) %>
      </td>
    </tr>
    <% if !@submission.message.blank? %>
    <tr>
      <td valign='top'>
        <strong><%= t('.message') %></strong>
      </td>
      <td>
        <%= simple_format @submission.message, :style => 'margin-top: 0' %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/submissions/_form.html.erb
<%= form_for Submission.new do |f| -%>
  <div class='field'>
    <%= f.label :first_name -%>
    <%= f.text_field :first_name  -%>
  </div>
  
  <div class='field'>
    <%= f.label :last_name -%>
    <%= f.text_field :last_name  -%>
  </div>
  
  <div class='field'>
    <%= f.label :email -%>
    <%= f.text_field :email  -%>
  </div>
  
  <div class='field'>
    <%= f.label :phone -%>
    <%= f.text_field :phone  -%>
  </div>
  
  <div class='field'>
    <%= f.label :your_interest -%>
    <%= f.text_field :your_interest  -%>
  </div>
  
  <div class='field'>
    <%= f.label :how_did_you_find_us -%>
    <%= f.text_field :how_did_you_find_us  -%>
  </div>
  
  <div class='field'>
    <%= f.label :newsletter -%>
    <%= f.check_box :newsletter  -%>
  </div>
  
  <div class='field'>
    <%= f.label :method_of_contact -%>
    <%= f.text_field :method_of_contact  -%>
  </div>
  
  <div class='field'>
    <%= f.label :message -%>
    <%= f.text_area :message  -%>
  </div>
  
  <div class='actions'>
    <%= f.submit t('.send') %>
  </div>
  
<% end -%>

app/views/submissions/new.html.erb
<% content_for :body_content_left do %>
  <div class="inquiries">
    <%=raw @page.content_for(Page.default_parts.first.to_sym) %>
    <%= render :partial => "form" %>
  </div>
<% end %>
<%= render :partial => '/shared/content_page' %>

app/views/submissions/thank_you.html.erb
<%= render :partial => "/shared/content_page" %>